apiVersion: v1
kind: Secret
type: Opaque
metadata:
  annotations:
    managed-by: argocd.argoproj.io
  labels:
    argocd.argoproj.io/secret-type: repository
  namespace: argocd
  name: arc-v1-chart-repo
data:
  # true
  # enableOCI: dHJ1ZQ==
  # actions-runner-controller
  name: YWN0aW9ucy1ydW5uZXItY29udHJvbGxlcg==
  # arc-v1
  project: YXJjLXYx
  # type: helm
  type: aGVsbQ==
  # https://actions-runner-controller.github.io/actions-runner-controller
  url: aHR0cHM6Ly9hY3Rpb25zLXJ1bm5lci1jb250cm9sbGVyLmdpdGh1Yi5pby9hY3Rpb25zLXJ1bm5lci1jb250cm9sbGVy
