apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: arc
  namespace: arc-system
  # Finalizer that ensures that project is not deleted until it is not referenced by any application
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  # Project description
  description: Project for actions runner controller

  # Allow manifests to deploy from any Git repos
  sourceRepos:
  - '*'

  # Only permit applications to deploy to the guestbook namespace in the same cluster
  destinations:
  - namespace: arc-system
    server: https://kubernetes.default.svc
  - namespace: arc-runners
    server: https://kubernetes.default.svc

